#!/bin/bash
picom & disown
dunst & disown
fcitx5 & disown
killall -q polybar
polybar & disown
feh --randomize --bg-fill --auto-zoom wallpaper
xsetroot -cursor_name left_ptr


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 壹 贰 叁 肆 伍

bspc config border_width         4
bspc config window_gap           7

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc config focused_border_color "#b48ead"
bspc config normal_border_color "#d08770"
